Merged PR 8335940: Add integration test
# Overview

* Add a basic integration test to deploy a solution, target, instance manifest
* Tests are split up into suites (folders)
  * Each folder has an independent magefile to handle setup, cleanup, and running tests.
  * Symphony is deployed at the start of each suite
  * Clean up will happen after the folder is done
* A test will
  * Deploy symphony before starting
  * Apply manifests for the test
  * Run test code using the go unit test framework
    * Tests can use the k8s client library to access the cluster and verify pods and status
* Added `Up` and other commands for use when developing with the localenv

## Test output
```
Searching for integration tests
Running tests in: /mnt/vss/_work/1/s/test/integration/scenarios/basic/test.yaml
Starting suite: /mnt/vss/_work/1/s/test/integration/scenarios/basic/test.yaml
>  cd ../../localenv && mage deploy
> helm upgrade ecosystem ../symphony-extension/helm/symphony-chart --install -n default --create-namespace --wait -f symphony-chart-values.yaml
Release "ecosystem" does not exist. Installing it now.
NAME: ecosystem
LAST DEPLOYED: Tue Jun 27 06:41:57 2023
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None

Starting test: deploy manifest
> kubectl apply -f /mnt/vss/_work/1/s/test/integration/scenarios/basic/manifest/target.yaml
target.symphony.microsoft.com/self created
> kubectl apply -f /mnt/vss/_work/1/s/test/integration/scenarios/basic/manifest/instance.yaml
instance.symphony.microsoft.com/instance created
> kubectl apply -f /mnt/vss/_work/1/s/test/integration/scenarios/basic/manifest/solution.yaml
solution.symphony.microsoft.com/my-sol created
Waiting for all pods to become ready...
waiting for ready state. Try: 30 Not ready: selftest, scheduler, worker
waiting for ready state. Try: 60 Not ready: selftest, scheduler, worker
waiting for ready state. Try: 90 Not ready: selftest, scheduler, worker
waiting for ready state. Try: 120 Not ready: selftest, scheduler, worker
waiting for ready state. Try: 150 Not ready: selftest, scheduler, worker
waiting for ready state. Try: 180 Not ready: selftest, worker
All pods are ready:  3m33.997811895s
> go test -timeout 10m /mnt/vss/_work/1/s/test/integration/scenarios/basic/verify/...
go: downloading k8s.io/apimachinery v0.27.3
go: downloading github.com/stretchr/testify v1.8.4
go: downloading k8s.io/client-go v0.27.3
go: downloading k8s.io/klog/v2 v2.90.1
go: downloading github.com/google/gofuzz v1.1.0
go: downloading golang.org/x/net v0.8.0
go: downloading k8s.io/utils v0.0.0-20230209194617-a36077c30491
go: downloading github.com/imdario/mergo v0.3.6
go: downloading golang.org/x/term v0.6.0
go: downloading sigs.k8s.io/json v0.0.0-20221116044647-bc3834ca7abd
go: downloading k8s.io/api v0.27.3
go: downloading github.com/golang/protobuf v1.5.3
go: downloading golang.org/x/oauth2 v0.0.0-20220223155221-ee480838109b
go: downloading k8s.io/kube-openapi v0.0.0-20230501164219-8b0f38b5fd1f
go: downloading golang.org/x/text v0.8.0
go: downloading g...

diff --git a/.pipelines/IntegrationTestsPR.yml b/.pipelines/IntegrationTestsPR.yml
--- a/.pipelines/IntegrationTestsPR.yml
+++ b/.pipelines/IntegrationTestsPR.yml
@@ -37,16 +37,20 @@ steps:
       export MINIKUBE_HOME="$(pwd)/.minikube"
       echo "MINIKUBE_HOME: $MINIKUBE_HOME"
 
-      # fail on errors
-      set -e
+      # Add mage to path
+      export PATH=$HOME/go/bin:$PATH
 
+      # fail on errors
+      set -e      
+     
       # load up minikube
       
       pushd localenv
-      $HOME/go/bin/mage SetupIntegrationTests
+      mage SetupIntegrationTests
       popd
       
       # run integration tests
-      # TODO add tests
+      pushd test/integration
+      mage Test
       
       echo "DONE! exit: $?"
